# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac38074a706c4439486eeec8437bc83c56d41ef652662ed8c90f12eab724aad699be6dc6805bbd7cc15e15d39df51345d52c6ccc008bdb008169bfc2e869e511

test:
  secret_key_base: 15265bd852ba7834dc17af8bc0a67483c087e039c7c875c4eba56cf5bc686dbaad55c90dfd1695df3cee47b061b1559a8c31eb9ee9ec7372666fcdcd1c7f2ab8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
